multitool/config/routes.rb
Rails.application.routes.draw do

  # Notes App -- ReactNative
  resources :notes
  get 'reverse_geocode/', to: 'reverse_geocode#reverse_geocode'

  # Todos App -- RubyMotion
  resources :todos

  # World Clock App -- Web
  get 'clock/time_zones'

  # Weather Forecast App -- iOS
  match 'weather/', to: 'weather#index', as: :weather, via: [:get, :post]
  get 'weather/location'
  get 'weather/:zip', to: 'weather#zip', as: :weather_for_zip

  # Currency Conversion App -- Android/Xamarin
  match 'convert/', to: 'convert#index', as: :convert, via: [:get, :post]
  get 'convert/:from_currency/:to_currency', to: 'convert#convert', as: :convert_result, from_currency: /[A-Za-z]{3}/, to_currency: /[A-Za-z]{3}/

  # Stock Quotes App -- Windows
  match 'stock_quotes/:symbols', to: 'stock_quotes#index', as: :stock_quotes, via: [:get]

end

multitool/app/controllers/convert_controller.rb
class ConvertController < ActionController::Base

  def index
    if request.post? and (params[:from_currency] and params[:to_currency])
      redirect_to convert_result_url from_currency: params[:from_currency], to_currency: params[:to_currency], amount: params[:amount]
    else
      render "convert/index"
    end
  end

  # START: convert
  def convert
    # Uncomment to make this call run long
    # sleep 10.seconds
    @from_currency = params[:from_currency]
    @to_currency = params[:to_currency]
    @conversion = CurrencyConversion.for(params[:from_currency], params[:to_currency])
    @amount = params[:amount]
    @conversion_amount = @conversion.for_amount(@amount)
    render "convert/convert"
  end
  # END: convert

end

multitool/app/views/convert/convert.html.erb
<p><%= @conversion.name %>: <%= @conversion.rate %>.</p>
<% if @amount %>
  <p><%= @amount %><%= @from_currency %> = <%= @conversion_amount %> <%= @to_currency %></p>
<% end %>

multitool/app/views/convert/index.html.erb
<h1>Convert Currency</h1>

<%= form_tag(convert_url) do %>
  <div class="actions">
    <%= label_tag(:from_currency, "From Currency:") %>
    <%= text_field_tag(:from_currency) %>
    <br/>
    <%= label_tag(:to_currency, "To Currency:") %>
    <%= text_field_tag(:to_currency) %>
    <br/>
    <%= label_tag(:amount, "Amount: [Optional]") %>
    <%= text_field_tag(:amount) %>
    <br/>
    <%= submit_tag("Convert") %>
  </div>
<% end %>