multitool/config/routes.rb
Rails.application.routes.draw do

  # Notes App -- ReactNative
  resources :notes
  get 'reverse_geocode/', to: 'reverse_geocode#reverse_geocode'

  # Todos App -- RubyMotion
  resources :todos

  # World Clock App -- Web
  get 'clock/time_zones'

  # Weather Forecast App -- iOS
  match 'weather/', to: 'weather#index', as: :weather, via: [:get, :post]
  get 'weather/location'
  get 'weather/:zip', to: 'weather#zip', as: :weather_for_zip

  # Currency Conversion App -- Android/Xamarin
  match 'convert/', to: 'convert#index', as: :convert, via: [:get, :post]
  get 'convert/:from_currency/:to_currency', to: 'convert#convert', as: :convert_result, from_currency: /[A-Za-z]{3}/, to_currency: /[A-Za-z]{3}/

  # Stock Quotes App -- Windows
  match 'stock_quotes/:symbols', to: 'stock_quotes#index', as: :stock_quotes, via: [:get]

end

multitool/app/models/todo.rb
class Todo < ActiveRecord::Base
end

multitool/app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :set_todo, only: [:show, :edit, :update, :destroy]

  # GET /todos
  # GET /todos.json
  def index
    @todos = Todo.all
  end

  # GET /todos/1
  # GET /todos/1.json
  def show
  end

  # GET /todos/new
  def new
    @todo = Todo.new
  end

  # GET /todos/1/edit
  def edit
  end

  # POST /todos
  # POST /todos.json
  def create
    @todo = Todo.new(todo_params)

    respond_to do |format|
      if @todo.save
        format.html { redirect_to @todo, notice: 'Todo was successfully created.' }
        format.json { render :show, status: :created, location: @todo }
      else
        format.html { render :new }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todos/1
  # PATCH/PUT /todos/1.json
  def update
    respond_to do |format|
      if @todo.update(todo_params)
        format.html { redirect_to @todo, notice: 'Todo was successfully updated.' }
        format.json { render :show, status: :ok, location: @todo }
      else
        format.html { render :edit }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todos/1
  # DELETE /todos/1.json
  def destroy
    @todo.destroy
    respond_to do |format|
      format.html { redirect_to todos_url, notice: 'Todo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo
      @todo = Todo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def todo_params
      params.require(:todo).permit(:title, :complete)
    end
end

multitool/app/helpers/todos_helper.rb
module TodosHelper
end

multitool/app/views/todos/_form.html.erb
<%= form_for(@todo) do |f| %>
  <% if @todo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@todo.errors.count, "error") %> prohibited this todo from being saved:</h2>

      <ul>
      <% @todo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :complete %><br>
    <%= f.check_box :complete %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

multitool/app/views/todos/edit.html.erb
<h1>Editing todo</h1>

<%= render 'form' %>

<%= link_to 'Show', @todo %> |
<%= link_to 'Back', todos_path %>

multitool/app/views/todos/index.html.erb
<h1>Listing todos</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Complete</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @todos.each do |todo| %>
      <tr>
        <td><%= todo.title %></td>
        <td><%= todo.complete %></td>
        <td><%= link_to 'Show', todo %></td>
        <td><%= link_to 'Edit', edit_todo_path(todo) %></td>
        <td><%= link_to 'Destroy', todo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Todo', new_todo_path %>

multitool/app/views/todos/new.html.erb
<h1>New todo</h1>

<%= render 'form' %>

<%= link_to 'Back', todos_path %>

multitool/app/views/todos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @todo.title %>
</p>

<p>
  <strong>Complete:</strong>
  <%= @todo.complete %>
</p>

<%= link_to 'Edit', edit_todo_path(@todo) %> |
<%= link_to 'Back', todos_path %>