multitool/config/routes.rb
Rails.application.routes.draw do

  # Notes App -- ReactNative
  resources :notes
  get 'reverse_geocode/', to: 'reverse_geocode#reverse_geocode'

  # Todos App -- RubyMotion
  resources :todos

  # World Clock App -- Web
  get 'clock/time_zones'

  # Weather Forecast App -- iOS
  match 'weather/', to: 'weather#index', as: :weather, via: [:get, :post]
  get 'weather/location'
  get 'weather/:zip', to: 'weather#zip', as: :weather_for_zip

  # Currency Conversion App -- Android/Xamarin
  match 'convert/', to: 'convert#index', as: :convert, via: [:get, :post]
  get 'convert/:from_currency/:to_currency', to: 'convert#convert', as: :convert_result, from_currency: /[A-Za-z]{3}/, to_currency: /[A-Za-z]{3}/

  # Stock Quotes App -- Windows
  match 'stock_quotes/:symbols', to: 'stock_quotes#index', as: :stock_quotes, via: [:get]

end

multitool/app/models/note.rb
class Note < ActiveRecord::Base
end

multitool/app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :set_note, only: [:show, :edit, :update, :destroy]

  # GET /notes
  # GET /notes.json
  def index
    @notes = Note.all
  end

  # GET /notes/1
  # GET /notes/1.json
  def show
  end

  # GET /notes/new
  def new
    @note = Note.new
  end

  # GET /notes/1/edit
  def edit
  end

  # POST /notes
  # POST /notes.json
  def create
    @note = Note.new(note_params)

    respond_to do |format|
      if @note.save
        format.html { redirect_to @note, notice: 'Note was successfully created.' }
        format.json { render :show, status: :created, location: @note }
      else
        format.html { render :new }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notes/1
  # PATCH/PUT /notes/1.json
  def update
    respond_to do |format|
      if @note.update(note_params)
        format.html { redirect_to @note, notice: 'Note was successfully updated.' }
        format.json { render :show, status: :ok, location: @note }
      else
        format.html { render :edit }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notes/1
  # DELETE /notes/1.json
  def destroy
    @note.destroy
    respond_to do |format|
      format.html { redirect_to notes_url, notice: 'Note was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_note
      @note = Note.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def note_params
      params.require(:note).permit(:title, :body, :latitude, :longitude, :created_where)
    end
end

multitool/app/helpers/notes_helper.rb
module NotesHelper
end

multitool/app/views/notes/_form.html.erb
<%= form_for(@note) do |f| %>
  <% if @note.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@note.errors.count, "error") %> prohibited this note from being saved:</h2>

      <ul>
      <% @note.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_field :body %>
  </div>
  <div class="field">
    <%= f.label :latitude %><br>
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br>
    <%= f.text_field :longitude %>
  </div>
  <div class="field">
    <%= f.label :created_where %><br>
    <%= f.text_field :created_where %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

multitool/app/views/notes/edit.html.erb
<h1>Editing note</h1>

<%= render 'form' %>

<%= link_to 'Show', @note %> |
<%= link_to 'Back', notes_path %>

multitool/app/views/notes/index.html.erb
<h1>Listing notes</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th>Created where</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @notes.each do |note| %>
      <tr>
        <td><%= note.title %></td>
        <td><%= note.body %></td>
        <td><%= note.latitude %></td>
        <td><%= note.longitude %></td>
        <td><%= note.created_where %></td>
        <td><%= link_to 'Show', note %></td>
        <td><%= link_to 'Edit', edit_note_path(note) %></td>
        <td><%= link_to 'Destroy', note, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Note', new_note_path %>

multitool/app/views/notes/new.html.erb
<h1>New note</h1>

<%= render 'form' %>

<%= link_to 'Back', notes_path %>

multitool/app/views/notes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @note.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @note.body %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @note.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @note.longitude %>
</p>

<p>
  <strong>Created where:</strong>
  <%= @note.created_where %>
</p>

<%= link_to 'Edit', edit_note_path(@note) %> |
<%= link_to 'Back', notes_path %>